### ISSUE TITLE
feat: add `--token` option for every command

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/cli#28]
Currently it is always necessary to execute `capawesome login` once in CI/CD environments:

```yml
- name: Login to Capawesome Cloud
        run: npx capawesome login --token ${{ secrets.CAPAWESOME_CLOUD_TOKEN }}
- name: Create a bundle on Capawesome Cloud
  run: npx capawesome apps:bundles:create --appId 00000000-0000-0000-0000-000000000000 --path dist --channel ${{ github.event.inputs.channel }}
```

This should no longer be necessary in the future:

```yml
- name: Create a bundle on Capawesome Cloud
  run: npx capawesome apps:bundles:create --appId 00000000-0000-0000-0000-000000000000 --path dist --channel ${{ github.event.inputs.channel }} --token ${{ secrets.CAPAWESOME_CLOUD_TOKEN }}
```

Or alternatively:

```yml
- name: Create a bundle on Capawesome Cloud
  run: npx capawesome apps:bundles:create --appId 00000000-0000-0000-0000-000000000000 --path dist --channel ${{ github.event.inputs.channel }}
  env:
    CAPAWESOME_CLOUD_TOKEN: ${{ secrets.CAPAWESOME_CLOUD_TOKEN }}
```

Maybe we can find a way to add those global options in a single place so that it is not necessary to modify every command.
